### ISSUE TITLE
Please add a licence to the project

### ISSUE THREAD

**Issue by cstrobbe** [YangKuang/pinyin4net#1]
May I ask you to add a licence to the project? To me, the absence of a licence does not signal "You are free to use this code in any way you like" but "I'm not going to tell you what the licence is; reuse the code at your own (legal) risk". If your goal is to allow widespread reuse of your code, you may consider very liberal licences such as [Apache 2.0](http://www.apache.org/licenses/LICENSE-2.0), the [MIT license](https://mit-license.org/) or the [3-Clause BSD License](https://opensource.org/licenses/BSD-3-Clause). 

For background, see also [ Choose a License](https://choosealicense.com/) and [Pick a License, Any License](https://blog.codinghorror.com/pick-a-license-any-license/). 

Update: A licence is mentioned in the README, but there is no licence file in the project.

**Comment by YangKuang** [comment]
Hi cstrobbe, thanks for your suggestion. I have added a MIT license file in my project.
