### ISSUE TITLE
problem found

### ISSUE THREAD

**Issue by orecchionebruno** [YangKuang/pinyin4net#3]
I tried to convert the word 漂亮 into pinyin but for some reason the result is "piāo liàng" but in the Baidu dictionary I see that it must be "piào liang" .

A similar problem is with 这个 zhè gè instead zhè ge

May you please check ?

I must also say that I appreciate so much your great job!
It's easy to use your DLL!

**Comment by Roman-Lo** [comment]
Pinyin is the phonetic sign for mandarin. Tones might change for different context, just like in English the word 'read' pronounce 'reed' in present but 'red' in past tense.
I think this library is just for convert single Chinese character into its pinyin, regardless of the context (words, phases, paragraphs, etc..).

**Comment by YangKuang** [comment]
@orecchionebruno I think I can't fix this. This library is developed 9 years ago, and fix this problem need so much work to do. To solve this problem, we need backend service, and this library will no longer light weight and easy to use. This is not what we expected. If you really need this, some online service provide similar feature.

Just like @Roman-Lo said, this library is a very small library for convert single Chinese character into its pinyin.
